CREATE TABLE IF NOT EXISTS "product" (
  "id" SERIAL,
  "name" VARCHAR(255) NOT NULL,
  "price" NUMERIC NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("id")
);